name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag, e.g. 0.0.1'
        required: true
jobs:
  echo-stuff:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Branch name
        run: git branch -a
      - name: Version bump and tag
        run: |
          git config --global user.email "2401026+matthewgilbert@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          echo "__version__=${{ github.event.inputs.version }} > src/tester_project/__init__.py
          git add src/tester_project/__init__.py
          git commit -m "RLS: Update version for upcoming release ${{ github.event.inputs.version }}"
          git tag -a "v${{ github.event.inputs.version }}" -m "Version ${{ github.event.inputs.version }}"
          git push && git push --tags
