name: echoer
on: workflow_dispatch
jobs:
  echo-stuff:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Echo it
        run: echo "Hello from ${GITHUB_REF}"
      - name: Branch name
        run: git branch -a
      - name: Commit stuff
        run: |
          git checkout gh-pages
          touch great_file
          git config --global user.email "botman@bot.com"
          git config --global user.name "Ro Bot"
          git add great_file
          git commit -m "Automatic"
          git push
