name: echoer
on: workflow_dispatch
jobs:
  echo-stuff:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      run: Echo "only defined for master not ${GITHUB_REF}"
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Echo it
        run: echo "Hello"
      - name: Branch name
        run: git branch
