name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag, e.g. 0.0.1'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
      - name: Environment setup
        run: |
          git config --global user.email "2401026+matthewgilbert@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Build docs
        run: cd doc && make html
      - name: Commit docs
        run: |
          git checkout gh-pages
          echo $PWD
          cp doc/build/* .
          ls
