name: test-suite
on: [push]
jobs:
  runs-on: ubuntu-latest
  defaults:
    run:
      shell: bash -l {0}
  unittests:
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
      - name: Conda info
        run: conda info && conda list
      - run: pytest
  doc-build:
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
      - name: Build docs
        run: cd doc && make html
  package-build:
    steps:
      - name: Build package
        run: python -m build --sdist --wheel --outdir dist/
